Repository ucsb-cs156-m23/proj-happycows-m23-10am-2, pull requests merged in 2023-08, with the labels that each got.

#16 JZ - added Leaderboard Feature for totalWealth to be displayed in the desired format
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: Ready for staff review

#21 RG - Leaderboard Back Button + Tests
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 10

#27 CC - removed purchase pop ups
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Ready for staff review

#17 JZ- Commons Feature modified to allow degradation values to be set as low as 0.001 (steps)
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
Labels: 5, MergeCandidate-CI/CD

#23 ka - adds a warning window popping up upon attempting to delete a commons
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
Labels: 10, MergeCandidate-CI/CD

#26 ka - makes unhealthy cows cheaper to sell
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10, MergeCandidate-CI/CD

#31 JZ - UX FIX: Default values on Create Commons Form
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
Labels: Ready for staff review, MergeCandidate-CI/CD

#34 ka - a new Last Day Date entry (setting the end date of a game) + gameInProgress() function telling whether the game is ongoing
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
Labels: 10

#36 JZ - CommonStats
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonStats.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonStatsRepository.java
Labels: 5

#48 ka - makes automatic jobs only run on in-progress commons
  src/main/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: 10, MergeCandidate-CI/CD

#54 JZ - CommonStats all jobs and avg health and Endpoint
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobs.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonStatsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthService.java
  src/main/resources/application-development.properties
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthServiceTest.java
Labels: 10, MergeCandidate-CI/CD

#56 JZ - CommonStats CSV part of backend + tweaked Commons Controller tests
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelper.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10, MergeCandidate-CI/CD

#61 ka - reimplements effectiveCapacity issue
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonsPlus.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategies.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategy.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsPlusTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategyTests.java
Labels: 10
